/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JLabel;
import javax.swing.JTextField;
import net.ucanaccess.jdbc.UpdateResultSet;

/**
 *
 * @author Motile
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboardJframe
     */
    public AdminDashboard() {
        initComponents();       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cbxtournament = new javax.swing.JComboBox();
        cbxground = new javax.swing.JComboBox();
        cbxmatchdetails = new javax.swing.JComboBox();
        cbxenclosure = new javax.swing.JComboBox();
        cbxresult = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbladmins = new javax.swing.JLabel();

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jTextField5.setText("BOOK KARO YAR ;)");
        jTextField5.setBorder(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 100));

        jPanel1.setBackground(new java.awt.Color(204, 255, 153));

        jPanel2.setBackground(new java.awt.Color(102, 153, 0));

        cbxtournament.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        cbxtournament.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tournaments", "Add Tournament", "Delete Tournament", "Update Tournament", "Search Tournament" }));
        cbxtournament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxtournamentActionPerformed(evt);
            }
        });

        cbxground.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        cbxground.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grounds", "Add Ground", "Delete Ground", "Update Ground", "Search Ground" }));
        cbxground.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxgroundActionPerformed(evt);
            }
        });

        cbxmatchdetails.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        cbxmatchdetails.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Match Details", "Add Match Details", "Delete Match Details", "Update Match Details", "Search Match Details" }));
        cbxmatchdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxmatchdetailsActionPerformed(evt);
            }
        });

        cbxenclosure.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        cbxenclosure.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enclosures", "Add Enclosure", "Delete Enclosure", "Update Enclosure", "Search Enclosure" }));
        cbxenclosure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxenclosureActionPerformed(evt);
            }
        });

        cbxresult.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        cbxresult.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Results", "Specify Result" }));
        cbxresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxresultActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Signout");
        jButton1.setPreferredSize(new java.awt.Dimension(143, 62));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbxtournament, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cbxground, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cbxmatchdetails, 0, 270, Short.MAX_VALUE)
            .addComponent(cbxenclosure, 0, 270, Short.MAX_VALUE)
            .addComponent(cbxresult, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxtournament, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxground, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxmatchdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxenclosure, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxresult, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PCB-Logo-Small.png"))); // NOI18N

        lbladmins.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        lbladmins.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(305, 305, 305)
                .addComponent(lbladmins, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(445, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lbladmins)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        Home h=new Home();
        h.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbxtournamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxtournamentActionPerformed
        AddDeleteSearchTournament adst=new AddDeleteSearchTournament();
        UpdateTournament ut=new UpdateTournament();
        if(cbxtournament.getSelectedItem()=="Add Tournament")
        {
            setVisible(false);
            adst.setVisible(true);
        }
        else if(cbxtournament.getSelectedItem()=="Delete Tournament")
        {
            setVisible(false);
            adst.setVisible(true);
        }
        else if(cbxtournament.getSelectedItem()=="Update Tournament")
        {
            setVisible(false);
            ut.setVisible(true);
        }
        else if(cbxtournament.getSelectedItem()=="Search Tournament")
        {
            setVisible(false);
            adst.setVisible(true);
        }
    }//GEN-LAST:event_cbxtournamentActionPerformed

    private void cbxgroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxgroundActionPerformed
        SearchDeleteGround sdg=new SearchDeleteGround();
        AddUpdateGround aug=new AddUpdateGround();
        if(cbxground.getSelectedItem()=="Add Ground")
        {
            setVisible(false);
            aug.setVisible(true);
        }
        else if(cbxground.getSelectedItem()=="Delete Ground")
        {
            setVisible(false);
            sdg.setVisible(true);
        }
        else if(cbxground.getSelectedItem()=="Update Ground")
        {
            setVisible(false);
            aug.setVisible(true);
        }
        else if(cbxground.getSelectedItem()=="Search Ground")
        {
            setVisible(false);
            sdg.setVisible(true);
        }
    }//GEN-LAST:event_cbxgroundActionPerformed

    private void cbxmatchdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxmatchdetailsActionPerformed
        AddUpdateMatchdetails aum=new AddUpdateMatchdetails();
        SearchDeleteMatchdetails sdm=new SearchDeleteMatchdetails();
        if(cbxmatchdetails.getSelectedItem()=="Add Match Details")
        {
            setVisible(false);
            aum.setVisible(true);
        }
        else if(cbxmatchdetails.getSelectedItem()=="Delete Match Details")
        {
            setVisible(false);
            sdm.setVisible(true);
        }
        else if(cbxmatchdetails.getSelectedItem()=="Update Match Details")
        {
            setVisible(false);
            aum.setVisible(true);
        }
        else if(cbxmatchdetails.getSelectedItem()=="Search Match Details")
        {
            setVisible(false);
            sdm.setVisible(true);
        }
    }//GEN-LAST:event_cbxmatchdetailsActionPerformed

    private void cbxenclosureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxenclosureActionPerformed
        AddUpdateEnclosure aue=new AddUpdateEnclosure();
        SearchDeleteEnclosure sde=new SearchDeleteEnclosure();
        if(cbxenclosure.getSelectedItem()=="Add Enclosure")
        {
            setVisible(false);
            aue.setVisible(true);
        }
        else if(cbxenclosure.getSelectedItem()=="Delete Enclosure")
        {
            setVisible(false);
            sde.setVisible(true);
        }
        else if(cbxenclosure.getSelectedItem()=="Update Enclosure")
        {
            setVisible(false);
            aue.setVisible(true);
        }
        else if(cbxenclosure.getSelectedItem()=="Search Enclosure")
        {
            setVisible(false);
            sde.setVisible(true);
        }
    }//GEN-LAST:event_cbxenclosureActionPerformed

    private void cbxresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxresultActionPerformed
        if(cbxresult.getSelectedItem()=="Specify Result")
        {
            SpecifyResult sr=new SpecifyResult();
            sr.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_cbxresultActionPerformed
    public void setAdminName(String adminsname)
    {
        lbladmins.setText(adminsname);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxenclosure;
    private javax.swing.JComboBox cbxground;
    private javax.swing.JComboBox cbxmatchdetails;
    private javax.swing.JComboBox cbxresult;
    private javax.swing.JComboBox cbxtournament;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lbladmins;
    // End of variables declaration//GEN-END:variables

   
}
