/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Admin.Admin;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import ticketbookingsystem.Ground;
import ticketbookingsystem.MatchDetails;
import ticketbookingsystem.Teams;

/**
 *
 * @author Motile
 */
public class SearchDeleteMatchdetails extends javax.swing.JFrame {
private ArrayList<MatchDetails> mList;
private Teams t;
private Ground g;
private MatchDetails m;
    /**
     * Creates new form SearchDeleteMatchdetails
     */
    public SearchDeleteMatchdetails() {
        initComponents();
        m=new MatchDetails();
        mList=m.getAllMatchDetails();
        loadTable();
    }
    public void loadTable(){
    DefaultTableModel model = (DefaultTableModel) tbl_matchdetails.getModel();
    
    for (int i = 0; i < mList.size(); i++) {
    m = mList.get(i);   
    g=m.getG();
        System.out.println(g.getName());
    t=m.getT();
        model.addRow(new Object[] {m.getId(),m.getmType(),m.getDate(),m.getTime(),t.getTeam(0),t.getTeam(1),m.getGenre(),g.getName(),g.getVenue(),g.getTotalcapacity(),m.getResult()});
    }
}
    Admin a=new Admin();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cbxtournament = new javax.swing.JComboBox();
        cbxground = new javax.swing.JComboBox();
        cbxmatchdetails = new javax.swing.JComboBox();
        cbxenclosure = new javax.swing.JComboBox();
        cbxresult = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_matchdetails = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PCB-Logo-Small.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 255, 153));

        jButton4.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(102, 153, 0));

        cbxtournament.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        cbxtournament.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tournaments", "Add Tournament", "Delete Tournament", "Update Tournament", "Search Tournament" }));
        cbxtournament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxtournamentActionPerformed(evt);
            }
        });

        cbxground.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        cbxground.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grounds", "Add Ground", "Delete Ground", "Update Ground", "Search Ground" }));
        cbxground.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxgroundActionPerformed(evt);
            }
        });

        cbxmatchdetails.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        cbxmatchdetails.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Match Details", "Add Match Details", "Delete Match Details", "Update Match Details", "Search Match Details" }));
        cbxmatchdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxmatchdetailsActionPerformed(evt);
            }
        });

        cbxenclosure.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        cbxenclosure.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enclosures", "Add Enclosure", "Delete Enclosure", "Update Enclosure", "Search Enclosure" }));
        cbxenclosure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxenclosureActionPerformed(evt);
            }
        });

        cbxresult.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        cbxresult.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Results", "Specify Result" }));
        cbxresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxresultActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back paint.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbxtournament, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cbxground, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cbxmatchdetails, 0, 270, Short.MAX_VALUE)
            .addComponent(cbxenclosure, 0, 270, Short.MAX_VALUE)
            .addComponent(cbxresult, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(cbxtournament, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxground, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxmatchdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxenclosure, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxresult, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("ID");

        tbl_matchdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Type", "Date", "Time", "TeamA", "TeamB", "Genre", "Ground", "Venue", "Capacity", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_matchdetails.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbl_matchdetails);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 550, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 950, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String mid=txtid.getText();
        a.searchMatchDetails(mid);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       String mid=txtid.getText();
        a.deleteMatchDetails(mid);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbxtournamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxtournamentActionPerformed
        AddDeleteSearchTournament adst=new AddDeleteSearchTournament();
        UpdateTournament ut=new UpdateTournament();
        if(cbxtournament.getSelectedItem()=="Add Tournament")
        {
            setVisible(false);
            adst.setVisible(true);
        }
        else if(cbxtournament.getSelectedItem()=="Delete Tournament")
        {
            setVisible(false);
            adst.setVisible(true);
        }
        else if(cbxtournament.getSelectedItem()=="Update Tournament")
        {
            setVisible(false);
            ut.setVisible(true);
        }
        else if(cbxtournament.getSelectedItem()=="Search Tournament")
        {
            setVisible(false);
            adst.setVisible(true);
        }
    }//GEN-LAST:event_cbxtournamentActionPerformed

    private void cbxgroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxgroundActionPerformed
        SearchDeleteGround sdg=new SearchDeleteGround();
        AddUpdateGround aug=new AddUpdateGround();
        if(cbxground.getSelectedItem()=="Add Ground")
        {
            setVisible(false);
            aug.setVisible(true);
        }
        else if(cbxground.getSelectedItem()=="Delete Ground")
        {
            setVisible(false);
            sdg.setVisible(true);
        }
        else if(cbxground.getSelectedItem()=="Update Ground")
        {
            setVisible(false);
            aug.setVisible(true);
        }
        else if(cbxground.getSelectedItem()=="Search Ground")
        {
            setVisible(false);
            sdg.setVisible(true);
        }
    }//GEN-LAST:event_cbxgroundActionPerformed

    private void cbxmatchdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxmatchdetailsActionPerformed
        AddUpdateMatchdetails aum=new AddUpdateMatchdetails();
        SearchDeleteMatchdetails sdm=new SearchDeleteMatchdetails();
        if(cbxmatchdetails.getSelectedItem()=="Add Match Details")
        {
            setVisible(false);
            aum.setVisible(true);
        }
        else if(cbxmatchdetails.getSelectedItem()=="Delete Match Details")
        {
            setVisible(false);
            sdm.setVisible(true);
        }
        else if(cbxmatchdetails.getSelectedItem()=="Update Match Details")
        {
            setVisible(false);
            aum.setVisible(true);
        }
        else if(cbxmatchdetails.getSelectedItem()=="Search Match Details")
        {
            setVisible(false);
            sdm.setVisible(true);
        }
    }//GEN-LAST:event_cbxmatchdetailsActionPerformed

    private void cbxenclosureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxenclosureActionPerformed
        AddUpdateEnclosure aue=new AddUpdateEnclosure();
        SearchDeleteEnclosure sde=new SearchDeleteEnclosure();
        if(cbxenclosure.getSelectedItem()=="Add Enclosure")
        {
            setVisible(false);
            aue.setVisible(true);
        }
        else if(cbxenclosure.getSelectedItem()=="Delete Enclosure")
        {
            setVisible(false);
            sde.setVisible(true);
        }
        else if(cbxenclosure.getSelectedItem()=="Update Enclosure")
        {
            setVisible(false);
            aue.setVisible(true);
        }
        else if(cbxenclosure.getSelectedItem()=="Search Enclosure")
        {
            setVisible(false);
            sde.setVisible(true);
        }
    }//GEN-LAST:event_cbxenclosureActionPerformed

    private void cbxresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxresultActionPerformed
        if(cbxresult.getSelectedItem()=="Specify Result")
        { 
            SpecifyResult sr=new SpecifyResult();
            sr.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_cbxresultActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        setVisible(false);
        AdminDashboard ad=new AdminDashboard();
        ad.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchDeleteMatchdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchDeleteMatchdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchDeleteMatchdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchDeleteMatchdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchDeleteMatchdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxenclosure;
    private javax.swing.JComboBox cbxground;
    private javax.swing.JComboBox cbxmatchdetails;
    private javax.swing.JComboBox cbxresult;
    private javax.swing.JComboBox cbxtournament;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_matchdetails;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
